# Generated by Selenium IDE
import time
from selenium import webdriver
from random import randrange
from phone_gen import PhoneNumber


i =0
adress = [""]
phones = [""]
names = ["Alex Smith"]
countries = ["Alabama,Alabama"]
result = "not found"
print(len(names))
for i in range(len(names)):
    print("ok")

    if countries[i] !=result:
        full_name = names [i]
        first = full_name.split()
        name = first[0]+"-"+first[-1]
        city = countries[i]
        count = []
        count = city.split(",")
        city = count[0]
        state = count[len(count)-1]
        driver = webdriver.Chrome()
        cook = True
        time.sleep(5)
        driver.get("https://www.usphonebook.com/"+name+"/"+city+"/"+state)
        i = 0
        while(cook == True):        
            try:
                print("enter try chrome")
                time.sleep(3)
                driver.find_element_by_class_name("g-recaptcha-response")
                print("recaptca avlble")
                driver.delete_all_cookies()
                # time.sleep(3)
                driver.refresh()
                cook = True
                i = i+1
            except :
                print("enter except chrome")
                cook = False              
            if(i==3):
                driver.quit()
                break
##        if(cook == True):
##                
##            driver = webdriver.Edge(executable_path  = 'C:\\Users\\user\\Desktop\\scrapping\\operadriver.exe')
##            time.sleep(5)
##            driver.get("https://www.usphonebook.com/"+"alex-smith"+"/"+"alabama"+"/"+"albama")
##            j = 0
##            while(cook):       
##                try:  
##                    print("enter try edge")
##
##                    time.sleep(3)
##                    driver.find_element_by_class_name("g-recaptcha-response")
##                    cook = True
##                    time.sleep(3)
##                    print("Captcha availble")
##
##                    driver.delete_all_cookies()
##                    driver.refresh()
##                    cook = True
##                    j = j+1                    
##                except :
##                    print("Enter except edge")
##
##                    cook = False
##                if(j==3):
##                    driver.quit()                   
##                    break
        if cook == True:
            print("captcha not passed")
        else:            
            driver.maximize_window()
            time.sleep(5)
            try:                    
                driver.find_element_by_xpath("//div[2]/div/div/div/a/span").click()
                numb = driver.find_element_by_class_name( "ls_success-blue-link").get_attribute('href')
                numb = (numb.split('/')[-1])
                phones[i] = numb.replace("-","")
            except :
                pn = (PhoneNumber('US').get_number())
                print(pn.replace("+1",""))            
            try:               
                adr = driver.find_element_by_class_name( "ls_contacts__text").text
                adr = adr.strip()
                adress[i] = adr      
                driver.quit()
            except :
                driver.quit()
    else:
        pass

        

            
